### ISSUE TITLE
Download link is pointing directly to Docker?

### ISSUE THREAD

**Issue by thadguidry** [kdhrubo/db2rest#130] opened 2024-01-12 12:11 UTC
README has this:

> In order to download the latest edition(v-0.0.8) of DB2Rest click `[here](https://www.docker.com/get-started/)`.

that link is Docker get-started?!?!

**Comment by kdhrubo** [comment] 2024-01-13 05:20
@thadguidry - please check and close this ticket if the issue is resolved

**Comment by thadguidry** [comment] 2024-01-13 09:03
Not resolved.  Wrong section edited.  Fix under the
### 2. Download DB2Rest

This line:  https://github.com/kdhrubo/db2rest/blob/fe8f84178b5ab9c388aaeeb83649fa549ba210ef/README.md?plain=1#L69

**Comment by kdhrubo** [comment] 2024-01-17 04:44
@thadguidry - fixed now pls review and close :)

**Closed** 2024-01-18 07:17 UTC
Labels: documentation
